version: 2
jobs:
  step1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
        name: Check for existing git tags
        command: |
        [[  $CIRCLE_TAG && ${CIRCLE_TAG-x} ]] && echo "Tag Found: $CIRCLE_TAG" || echo "No tag was found - no deployment will happen"
  step2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
        name: Check for existing git tags
        command: |
        [[  $CIRCLE_TAG && ${CIRCLE_TAG-x} ]] && echo "Tag Found: $CIRCLE_TAG" || echo "No tag was found - no deployment will happen"
workflows:
  version: 2
  tagged-build:
    jobs:
      - step1
      - step2:
          requires:
            - step1
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
