version: 2
jobs:
  step1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
  step2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
workflows:
  version: 2
  untagged-build:
    jobs:
      - step1:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)+$/
      - step2:
          requires:
            - step1
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)+$/
  tagged-build:
    jobs:
      - step1:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
      - step2:
          requires:
            - step1
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
