version: 2
jobs:
  step1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  step2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  step1-step2:
    jobs:
      - step1
      - approve:
          type: approval
          requires:
            - step1
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - step2:
          requires:
            - approve
