version: 2
jobs:
  step1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
  step2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
workflows:
  version: 2
  untagged-build:
    jobs:
      - step1
  tagged-build:
    jobs:
      - step1
      - step2:
          requires:
            - step1
          filters:
            tags:
              only: /^v.*/
