version: 2
jobs:
  step1:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
  step2:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
  step3:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
  step4:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print CIRCLE CI Env
          command: printenv | grep CIRCLE
      - run:
          name: Check for existing git tags
          command: |
            echo "CIRCLE_TAG: $CIRCLE_TAG"
            echo "CIRCLE_TAG-x: ${CIRCLE_TAG-x}"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - step1
      - step2:
          requires:
            - step1
      - approve:
          type: approval
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
            branches:
              ignore: /.*/
      - step3:
          requires:
            - approve
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
            branches:
              ignore: /.*/
      - step4:
          requires:
            - step3
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)+$/
            branches:
              ignore: /.*/
